name: 自动运行代码

on:
  schedule:
    # 设置为 UTC 12:00 (北京时间 8:00)
    - cron: '0 0 * * *'  # UTC 时间每天下午 12:00，等同于北京时间早上 8:00
  workflow_dispatch: # 允许手动触发

jobs:
  run_code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python (如果需要其他环境可根据情况修改)
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # 设置需要的 Python 版本

      - name: Install dependencies (根据需要修改)
        run: |
          pip install -r requirements.txt

      - env:
          XUEHAO: ${{ secrets.XUHAO }}
          MIMA: ${{ secrets.MIMA }}
        run: python main.py
